{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "curity.fullname" . }}-profiles-xml
  labels:
        {{- include "curity.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"

data:
  profiles-xml: |-
    <config xmlns="http://tail-f.com/ns/config/1.0">
      <profiles xmlns="https://curity.se/ns/conf/base">
  {{- range $profile := .Values.curity.config.profiles }}
        <profile>
          <id>{{- $profile.id -}}</id>
          <settings>
            <authorization-server>
              <scopes>
      {{ range $scope := $profile.settings.authorizationServer.scopes -}}
      {{- include "curity.scopeTag" . | nindent 12 }}
      {{ end }}
              <scope>
              <client-store>
                <config-backed>
      {{ range $client := $profile.settings.authorizationServer.clientStore.configBacked -}}
      {{- include "curity.clientTag" . | nindent 16 }}
      {{ end }}
                </config-backed>
              </client-store>
            </authorization-server>
          </settings>
        </profile>
  {{- end }}
    </profiles>
    </config>
